projects:
  - name: argocd
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Argocd Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    orphanedResources:
      warn: false
applications:
  - name: argocd
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      helm:
        version: v3
        valueFiles:
          - values.yaml
          - ../../../../projects/argocd/argo-cd/values-override.yaml
      path: charts/argo-helm/charts/argo-cd
      repoURL: https://github.com/palmithor/gitops-argocd-crossplane.git
      targetRevision: HEAD
    syncPolicy:
      automated:
        prune: false
        selfHeal: true
  - name: argocd-apps
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      helm:
        version: v3
        valueFiles:
          - values.yaml
          - ../../../../projects/argocd/argocd-apps/values-override.yaml
      path: charts/argo-helm/charts/argocd-apps
      repoURL: https://github.com/palmithor/gitops-argocd-crossplane.git
      targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
